### PR TITLE
LIGHTQUARK-61, LIGHTQUARK-63, gateway improvement

### PR DESCRIPTION
**Pull request by emilianya**

### CODE REVIEW

**Comment by emilianya** [comment]
image
Observe new messages with bot badge on quarkvite

This means the bug is fixed

**Comment by emilianya** [comment]
Invalid event subscriptions complain like this:
image
(event previously attemptedEvent)

Not permitted event subscriptions complain like this:
image
(previously would not tell you what event you werent allowed)

**Comment by emilianya** [comment]
image
kitty for reviewer

**Review by nyakase — APPROVED** [review]
this kitty is peculiar... how did that happen

sillyposting :3333

**Pull request merged**
