### PR TITLE
Add "pisscord" to known clients list

### PR DESCRIPTION
**Pull request by mitchellonii**
yes, i am aware it only fully supports 8 capabilities im working on it

### CODE REVIEW

**Comment by emilianya** [comment]
Your capabilities.json is malformed:
```json
"channels.*",
"messages.*",
"users.*"
 ```
 Wildcard is not actually supported, however the entire unsupported array is optional (The server is smart and will fill in all missing capabilities as unsupported)

**Comment by mitchellonii** [comment]
resolved
https://github.com/mitchellonii/pisscord/commit/42ef7d152df0c0ab8f2a1a33dd4337c7dcb89d33

**Comment by emilianya** [comment]
Alright, nice.
However, I am not a fan of the misuse of [Discord](https://discord.com) branding.
Looking for input from others on if this client should be accepted to the official listing or not.
@Vukkyy @P3il4

**Comment by emilianya** [comment]
I've tagged Vukky and Shruc, but anyone else is free to provide input as well.

**Comment by mitchellonii** [comment]
Is it just the name/icon you have an issue with?

**Comment by emilianya** [comment]
The use of the Discord (old) logo and other assets are the main ones
The name on its own is fine i guess... but when paired with Discord assets... eehhhh...

**Comment by nyakase** [comment]
The Pisscord name itself is hilarious and I don't have an issue with that. However using their old logo, old logotype, and presumably font (I remember you were using GG Sans?) is... questionable...

-person who uses music they do not own the rights to in their client

**Comment by nyakase** [comment]
In addition, due to the client's theme of piss and using Discord branding... i swear the logo is just the discord canary icon

tell me if it isnt

i cant see the difference

**Comment by emilianya** [comment]
it uses old clyde, thats the difference

**Comment by mitchellonii** [comment]
Pisscord isn't using GGSans at the moment (I was planning to rip it but I guess not...)

I created this new logo which I'll deploy on the next build (if you don't have any issues with it):
piss

**Comment by emilianya** [comment]
oh my god

**Comment by mitchellonii** [comment]
https://pisscord-eebohtkqn-mitchellonii.vercel.app/

**Comment by P3il4** [comment]
i approve the pisscord

**Comment by emilianya** [comment]
image
How open are you to doing something about this text

**Comment by mitchellonii** [comment]
what do you suggest?

**Comment by emilianya** [comment]
not ripping off discord??

**Comment by mitchellonii** [comment]
thats the whole point of the client, also the Uni-Sans font family is free

**Comment by emilianya** [comment]
> thats the whole point of the client, also the Uni-Sans font family is free
image

The colors red and white are free too

**Comment by nyakase** [comment]
fwiw, the demo version used by pisscord is in fact a free download: https://www.fontfabric.com/fonts/uni-sans/

**Comment by emilianya** [comment]
\*gives up*

**Comment by nyakase** [comment]
:3

**Comment by emilianya** [comment]
image

**Pull request merged**
